### Obtain the main route "/"
GET http://localhost:3000/

### GET - Get a list of products
GET http://localhost:3000/products

### GET - Get all categories
GET http://localhost:3000/categories

### GET - Get product by ID
GET http://localhost:3000/products/660306bb7265a08bdc43de43

### GET - Obtain a search param for products
GET http://localhost:3000/products/search

###
GET http://localhost:3000/products/search?categories=6602f205b684b25d98c129ec

### POST - Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Macbook Pro M3 16' Negro Jet Black",
  "description": "Esta es una descripción de ejemplo para el producto",
  "image": "https://ejemplo.com/imagen.jpg",
  "images": ["https://ejemplo.com/imagen1.jpg", "https://ejemplo.com/imagen2.jpg"],
  "brand": "Marca de ejemplo",
  "price": 99.99,
  "categories": ["6602f205b684b25d98c129ec"],
  "countInStock": 100,
  "rating": 4.5,
  "numReviews": 10,
  "isFeatured": true,
  "dateCreated": "2024-03-27T12:00:00.000Z",
  "dateUpdated": "2024-03-27T12:00:00.000Z"
}

### PATCH - Update a product
PATCH http://localhost:3000/products/6603070f7265a08bdc43de47
Content-Type: application/json

{
  "price": 49.99
}

### DELETE - Delete a product
DELETE  http://localhost:3000/products/6601ee7e6075e5d2b5d0f256